#! /bin/bash

# mailmyip
#
# This script sends a mail every time the network comes up.
# The mail contains a time stamp and the obtained IP address.
#
# Use: mailmyip [interfacename]
#
# Author: San Bergmans
#         www.sbprojects.com
#

# Configuration variables
RPINAME="Raspberry Pi"
MAILTO="user@email.com"

# Get interface name from parameters
if [ $# -eq 0 ]
then
        IFC="eth0"
else
        IFC="$1"
fi

ifconfig $IFC &> /dev/null
if [ $? = 0 ]
then
	PRIVATE=$(ifconfig $IFC | grep "inet addr:" | awk '{ print $2 }')
	IPV6=$(ifconfig $IFC | grep "Scope:Global" | awk '{ print $3 }')
	PRIVATE=${PRIVATE:5}
fi

# Get current private IP address for the selected interface

WIFC="wlan0"

ifconfig $WIFC &> /dev/null
if [ $? = 0 ]
then
	WPRIVATE=$(ifconfig $WIFC | grep "inet addr:" | awk '{ print $2 }')
	WIPV6=$(ifconfig $WIFC | grep "Scope:Global" | awk '{ print $3 }')
	WPRIVATE=${WPRIVATE:5}
fi

#Exit if IP address is empty
if [ -z $PRIVATE ]
then
	if [ -z $WPRIVATE ]
	then
	    exit 0
	fi
fi

# Wait about 2 minutes for the RTC to be set after boot (in steps of 10 seconds)
for I in {1..12}
do
    sleep 10
    if [ $(date +%Y) != "1970" ]
    then
        # Yes! The clock is set. Find out what our public IP address is and send the message.
        PUBLIC=$(curl -s checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//')
        MSG="From:$MAILTO\nSubject:$RPINAME IP update\nDate: $(date +%F\ %T)\n\n"
        if [ -n $PRIVATE ]
	then
		MSG="$MSG $RPINAME wired $IFC now has IP-Address $PRIVATE.\n"
	fi
        if [ -n $WPRIVATE ]
	then
	       	MSG="$MSG $RPINAME wifi $WIFC now has IP-Address $WPRIVATE.\n"
	fi
        MSG="$MSG Its public address is $PUBLIC.\n$IPV6"
        #MSG="From:$MAILTO\nSubject:$RPINAME IP update\nDate: $(date +%F\ %T)\n\n$RPINAME $IFC now has IP-Address $PRIVATE.\nIts public address is $PUBLIC.\n$IPV6"
        #MSG="From:$MAILTO\nSubject:$RPINAME IP update\nDate: $(date +%F\ %T)\n\n$RPINAME $IFC now has IP-Address $PRIVATE.\n$IPV6"
        echo -e $MSG | sendmail  "$MAILTO"
        exit 0
    fi
done
